Repository Rishikesh-12/HacktoberFest2020, pull requests merged in 2020-10, with the labels that each got.

#285 Famous coin change problem in python
  Algorithms/Python/CoinChangeProblem.py
Labels: hacktoberfest

#304 Create Find Common Elements
  Basic Programs/Find Common Elements
Labels: hacktoberfest-accepted

#62 rudrabarad | Face Detection
  .all-contributorsrc
  Face Detection/Needed Packages.txt
  Face Detection/face_detection.py
  Face Detection/haarcascade_frontalface_default.xml
Labels: hacktoberfest-accepted

#70 basic functions for directed graph
  Directed Graph/directed_graph.hpp
  Directed Graph/main.cpp
Labels: hacktoberfest-accepted

#74 Added JavaScript mini projects
  JavaScript Mini Projects/Color Flipper Js/README.md
  JavaScript Mini Projects/Color Flipper Js/index.html
  JavaScript Mini Projects/Color Flipper Js/script.js
  JavaScript Mini Projects/Color Flipper Js/styles.css
Labels: hacktoberfest-accepted

#404 calculator using JS
  calculator.html
Labels: hacktoberfest-accepted

#401 MNIST digits classification with TF
  digits_classification.ipynb
  digits_classification.py
Labels: hacktoberfest-accepted

#400 Added my php project
  conn.php
  delete.php
  display.php
  insert.php
  update.php
Labels: hacktoberfest-accepted

#84 Topo Sort
  Basic Programs/CPP/Topological_Sorting.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#98 Add files via upload
  bfs.py
Labels: Hacktoberfest, good first issue, hacktoberfest-accepted

#99 added max-heap sort and selection sort programs
  Algorithms/C++/Sorting/max-heap-sort.cpp
  Algorithms/C++/Sorting/selection-sort.cpp
Labels: Hacktoberfest, good first issue, hacktoberfest-accepted

#435 Adding Anagrams.cpp to Basic Programs
  Basic Programs/Anagram.cpp
Labels: hacktoberfest-accepted

#438 Create Minimum operation.cpp
  Algorithms/C++/DynamicProgramming/Minimum operation.cpp
Labels: hacktoberfest-accepted

#439 Create Equilibrium point.cpp
  Basic Programs/Equilibrium point.cpp
Labels: hacktoberfest-accepted

#441 Create SwastikPattern.py
  Basic Programs/SwastikPattern.py
Labels: hacktoberfest-accepted

#443 Create StarPattern.cpp
  Basic Programs/StarPattern.cpp
Labels: hacktoberfest-accepted

#444 CPP Program to print full pyramid using *
  Basic Programs/fullpyramid.cpp
Labels: hacktoberfest-accepted

#445 Create fullpyramidwithnumber.cpp
  Basic Programs/fullpyramidwithnumber.cpp
Labels: hacktoberfest-accepted

#446 Inverted full pyramid using *
  Basic Programs/invertedpyramid
Labels: hacktoberfest-accepted

#458 Hackatoberfest
  Algorithms/C++/ReadMe.md
  Basic Programs/CheckArmstrongNumber.cpp
  Basic Programs/CheckLeapYear.cpp
  Basic Programs/Power.cpp
  Basic Programs/SwapTwo Numbers.cpp
  Python Gst Calculator/ReadMe.md
  TicTacToe/ReadMe.md
Labels: Hacktoberfest, good first issue, hacktoberfest-accepted

#459 Create TransposeMatrix.cpp
  Algorithms/C++/Searching/heap_sort.cpp
  Basic Programs/Addition.cpp
  Basic Programs/CPP/Factorial.cpp
  Basic Programs/TransposeMatrix.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#469 Rahul149 patch 1
  Basic Programs/Welcome Mat Pattern.py
Labels: good first issue, hacktoberfest-accepted

#117 Implement strStr()
  Basic Programs/CPP/ImplementStrStr.cpp
Labels: hacktoberfest-accepted

#133 add simple program
  Basic Programs/count_words_phrase.py
Labels: hacktoberfest-accepted

#147 Go algorithms
  Algorithms/Go/binary_search/binary_search.go
  Algorithms/Go/bubble_sort/bubble_sort.go
Labels: Hacktoberfest, hacktoberfest-accepted

#151 Added Right_angled_pyramid_pattern
  Algorithms/C++/Pyramid_Pattern/Half_pyramid.cpp
  Algorithms/C++/Pyramid_Pattern/Right_angle_pyramid.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#154 Added Dijkstra Algorithm
  Algorithms/C++/Dijkstra Algorithm.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#157 notification for drinking water using python
  Basic Programs/notification.py
Labels: Hacktoberfest, hacktoberfest-accepted

#159 anagrams.py
  Prime___checker.py
  anagrams.py
Labels: Hacktoberfest, hacktoberfest-accepted

#160 Basic Python programs
  Automate-whatsapp-msg-using-python.py
  Basic Programs/Basic Python programs
  Basic Programs/pdf-to-audio.py
  python_code_to_read_pdf_as_audio.py
Labels: Hacktoberfest, hacktoberfest-accepted

#166 java programs added0
  java/Anagram.java
  java/checkPrime.java
Labels: Hacktoberfest, hacktoberfest-accepted

#167 added selection sort
  Algorithms/C++/Sorting/selection_sort.cpp
  DoubleStars.py
Labels: Hacktoberfest, hacktoberfest-accepted

#169 Create Updating Elements of Array by Multiplication
  Basic Programs/UpdatingArrayMultiplications
Labels: Hacktoberfest, hacktoberfest-accepted

#174 Selection sort.cpp
  Algorithms/C++/Sorting/Selection_sort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#178 Added Java
  Algorithms/Java/stackOperations.java
Labels: Hacktoberfest, hacktoberfest-accepted

#183 RB Tree Insertion and Deletion in JAVA
  Red_Black_Tree/readme.md
  Red_Black_Tree/src/App.java
  Red_Black_Tree/src/RBTree.java
Labels: Hacktoberfest, hacktoberfest-accepted

#184 python number game
  number predict game
Labels: Hacktoberfest, hacktoberfest-accepted

#186 swapping two numbers without using a third variable.
  Basic Programs/swapping two numbers without a third variable.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#191 added some new projects
  crud_redux/.gitignore
  crud_redux/README.md
  crud_redux/package-lock.json
  crud_redux/package.json
  crud_redux/public/index.html
  crud_redux/src/App.js
  crud_redux/src/actions/contactAction.js
  crud_redux/src/components/contacts/AddContact.js
  crud_redux/src/components/contacts/Contact.js
  crud_redux/src/components/contacts/Contacts.js
  crud_redux/src/components/contacts/EditContact.js
  crud_redux/src/components/elements/Navbar.js
  crud_redux/src/constant/types.js
  crud_redux/src/index.js
  crud_redux/src/reducers/contactReducer.js
  crud_redux/src/reducers/index.js
  crud_redux/src/store.js
  crud_redux/src/styles/App.scss
  crud_redux/src/styles/index.scss
  personalChatApp/.gitignore
  personalChatApp/README.md
  personalChatApp/css/style.css
  personalChatApp/essentials/aztecs.jpg
  personalChatApp/essentials/bootstrap/bootstrap.min.css
  personalChatApp/essentials/bootstrap/bootstrap.min.js
  personalChatApp/essentials/jquery.slim.min.js
  personalChatApp/essentials/tone.mp3
  personalChatApp/index.html
  personalChatApp/js/client.js
  personalChatApp/nodeserver/.gitignore
  personalChatApp/nodeserver/index.js
  personalChatApp/nodeserver/package.json
  personalChatApp/readme_images/joined.png
  personalChatApp/readme_images/new-joined.png
  personalChatApp/readme_images/rel-path.png
  personalChatApp/readme_images/send-recieve.png
  rainbow_circles_in_canvas/css/style.css
  rainbow_circles_in_canvas/index.html
  rainbow_circles_in_canvas/js/index.js
Labels: Hacktoberfest, hacktoberfest-accepted

#163 States weather project added to the repository
  states-weather/states-weather/package-lock.json
  states-weather/states-weather/package.json
  states-weather/states-weather/server.js
  states-weather/states-weather/views/index.hbs
Labels: Hacktoberfest, hacktoberfest-accepted

#165 Lane detection at night project added to the repository
  Lane-detection-in-Night-Enviroment-using-Kalman-Filter-master/Final_withIPM.ipynb
  Lane-detection-in-Night-Enviroment-using-Kalman-Filter-master/README.md
  Lane-detection-in-Night-Enviroment-using-Kalman-Filter-master/small_nightRoad.mp4
Labels: Hacktoberfest, hacktoberfest-accepted

#102 Added Some CP Problems
  Basic Programs/Some CP Problems/Amazingjokepy
  Basic Programs/Some CP Problems/Anton and Polyhedrons.cxx
  Basic Programs/Some CP Problems/BeautifulMatrix263A.cxx
  Basic Programs/Some CP Problems/Bulbs.cxx
  Basic Programs/Some CP Problems/Cheap Travel 466A.cxx
  Basic Programs/Some CP Problems/CrazyComputer716A.cxx
  Basic Programs/Some CP Problems/Dima and Continuous Line 358A.cxx
  Basic Programs/Some CP Problems/DivisibilityProblem1328A.cxx
  Basic Programs/Some CP Problems/Domino 353A.cxx
  Basic Programs/Some CP Problems/Dreamoon and Stairs 476A.cxx
  Basic Programs/Some CP Problems/Dubstep 208A.cxx
  Basic Programs/Some CP Problems/Elephant.cxx
  Basic Programs/Some CP Problems/EquailizePricesAgain.cxx
  Basic Programs/Some CP Problems/Even Odds 318A.cxx
  Basic Programs/Some CP Problems/Expression 479A.cxx
  Basic Programs/Some CP Problems/Game With Sticks 451A.cxx
  Basic Programs/Some CP Problems/Games268A.cxx
  Basic Programs/Some CP Problems/Got any Grapes1114A.cxx
  Basic Programs/Some CP Problems/Helpful Maths 339A.cxx
  Basic Programs/Some CP Problems/Hulk705A.cxx
  Basic Programs/Some CP Problems/I Wanna Be the Guy 469A.cxx
  Basic Programs/Some CP Problems/Ilya and Bank Account 31A.cxx
  Basic Programs/Some CP Problems/Magnets344A.cxx
  Basic Programs/Some CP Problems/My problem count.ods
  Basic Programs/Some CP Problems/NewYear And Hurry 750A.cxx
  Basic Programs/Some CP Problems/Pashmak and Garden 459A.cxx
  Basic Programs/Some CP Problems/Petya and Strings. 112Acxx
  Basic Programs/Some CP Problems/Point on Spiral 279A.cxx
  Basic Programs/Some CP Problems/Presents136A.cxx
  Basic Programs/Some CP Problems/String Task118A.cxx
  Basic Programs/Some CP Problems/Team Olympiad 490A.cxx
  Basic Programs/Some CP Problems/Watermelon4A.cxx
  Basic Programs/Some CP Problems/Way Too Long Words 71A.cxx
  Basic Programs/Some CP Problems/Young Physicist69A.cxx
Labels: hacktoberfest-accepted

#153 Implementing radix and bucket sort in C++
  Algorithms/C++/Sorting/Bucket Sort.cpp
  Algorithms/C++/Sorting/Radix Sort.cpp
Labels: hacktoberfest-accepted

#162 A landing page of a online education added
  Html Landing Page/XYPO Lnading page/css/style.css
  Html Landing Page/XYPO Lnading page/images/Thumbs.db
  Html Landing Page/XYPO Lnading page/images/about.png
  Html Landing Page/XYPO Lnading page/images/background.png
  Html Landing Page/XYPO Lnading page/images/contact.png
  Html Landing Page/XYPO Lnading page/images/course.png
  Html Landing Page/XYPO Lnading page/images/facebook.png
  Html Landing Page/XYPO Lnading page/images/instagram.png
  Html Landing Page/XYPO Lnading page/images/linkedin.png
  Html Landing Page/XYPO Lnading page/images/logo.png
  Html Landing Page/XYPO Lnading page/images/menu.png
  Html Landing Page/XYPO Lnading page/images/offer.png
  Html Landing Page/XYPO Lnading page/images/pic-1.png
  Html Landing Page/XYPO Lnading page/images/pic-2.png
  Html Landing Page/XYPO Lnading page/images/pic-3.png
  Html Landing Page/XYPO Lnading page/images/twitter.png
  Html Landing Page/XYPO Lnading page/index.html
Labels: hacktoberfest-accepted

#137 Create KMP Algorithm
  Algorithms/C++/Searching/KMP Algorithm
Labels: hacktoberfest-accepted, help wanted

#576 Template for Login Form
  Login/form.html
  Login/style.css
Labels: hacktoberfest-accepted

#577 added reverse of a number
  java/reverse.java
Labels: good first issue, hacktoberfest-accepted

#571 Github API fetching repos vanilla Js project
  GithubAPIFetchingRepo/.gitignore
  GithubAPIFetchingRepo/index.html
  GithubAPIFetchingRepo/script.js
  GithubAPIFetchingRepo/style.css
Labels: good first issue, hacktoberfest-accepted

#202 Python Port Scanner
  port scanner.py
Labels: hacktoberfest-accepted

#203 This program can give the transpose of a matrix
  Basic Programs/CPP/TransposeOfMatrix.cpp
Labels: good first issue, hacktoberfest-accepted

#601 C program for Time Complexity plot of Bubble, Insertion and Selection sort
  C/C program for Time Complexity plot of Bubble, Insertion and Selection Sort
Labels: good first issue, hacktoberfest-accepted

#597 Create Pyramid Sequence
  Algorithms/C++/Pyramid_Pattern/Pyramid Sequence
Labels: good first issue, hacktoberfest-accepted

#606 Login files changed
  Login/form.html
  Login/style.css
Labels: good first issue, hacktoberfest-accepted

#223 MergeSort
  MergeSortAlgo/main.cpp
  MergeSortAlgo/readme.md
Labels: good first issue, hacktoberfest-accepted

#581 To Do Application using HTML, CSS and JS
  To-do/README.md
  To-do/app.js
  To-do/index.html
  To-do/style.css
Labels: good first issue, hacktoberfest-accepted

#631 Create N- Queens-Problem.java
  N- Queens-Problem.java
Labels: hacktoberfest-accepted

#515 Boostrap 4 Form Updated
  Algorithms/C++/Sorting/Selection_sort.cpp
  Basic Programs/CPP/Factorial.cpp
  Bootstrap/forms.html
  Html Landing Page/img/cameras/box_camera.jpg
  Html Landing Page/img/cameras/indoor-doome.jpg
  Html Landing Page/img/cameras/ir_bullet_camera.jpg
  Html Landing Page/img/cameras/ir_dome_camera.jpg
  Html Landing Page/img/cameras/proof-ir-door.jpg
  Html Landing Page/img/header.png
  Html Landing Page/img/header1.jpg
  Html Landing Page/img/header2.jpg
  Html Landing Page/img/header3.png
  Html Landing Page/img/header4.jpg
  Html Landing Page/img/header5.jpg
  Html Landing Page/img/image1.jpg
  Html Landing Page/img/image2.jpg
  Html Landing Page/img/image3.jpg
  Html Landing Page/img/index1.jpg
  Html Landing Page/img/installer.jpeg
  Html Landing Page/img/laptop.png
  Html Landing Page/img/lights.jpg
  Html Landing Page/img/logo.png
  Html Landing Page/img/media.jpg
  Html Landing Page/img/person1.jpg
  Html Landing Page/img/person2.jpg
  Html Landing Page/img/person3.jpg
  Html Landing Page/img/person4.jpg
  Html Landing Page/index.html
  Html Landing Page/style.css
Labels: hacktoberfest-accepted

#222 created a hello world in javascript
  Basic Programs/hi.js
Labels: hacktoberfest-accepted

#224 port scanner
  python_port_scanner.py
Labels: hacktoberfest-accepted

#279 To reverse the elements of array
  C/Array_Reversal.c
Labels: hacktoberfest-accepted

#257 Added Tkinter basics
  Tkinter Basics (Python)/tkinter_basics.py
Labels: hacktoberfest-accepted

#258 Added Linked List data structure
  LinkedList.py
Labels: hacktoberfest-accepted

#338 First commit
  HolaMundo/.idea/.gitignore
  HolaMundo/.idea/aws.xml
  HolaMundo/.idea/codeStyles/Project.xml
  HolaMundo/.idea/codeStyles/codeStyleConfig.xml
  HolaMundo/.idea/description.html
  HolaMundo/.idea/encodings.xml
  HolaMundo/.idea/misc.xml
  HolaMundo/.idea/modules.xml
  HolaMundo/.idea/project-template.xml
  HolaMundo/.idea/vcs.xml
  HolaMundo/HolaMundo.iml
  HolaMundo/out/production/HolaMundo/co/com/jsanta/remove_duplicates/Main.class
  HolaMundo/src/co/com/jsanta/remove_duplicates/Main.java
Labels: hacktoberfest-accepted

#330 calculate GCD using recursive program in python
  Basic Programs/gcd.py
  Basic Programs/lcm.py
Labels: good first issue, hacktoberfest-accepted

#328 inversion count algorithm
  Algorithms/C++/inversion_count.cpp
Labels: good first issue, hacktoberfest-accepted

#675 FacebookLoginPage by Rishav
  facebook-login-page/package.json
  facebook-login-page/public/index.html
  facebook-login-page/src/App.js
  facebook-login-page/src/Facebook.js
  facebook-login-page/src/Facebook.module.css
  facebook-login-page/src/index.js
  facebook-login-page/src/styles.css
Labels: good first issue, hacktoberfest-accepted

#263 Check Even Odd No in C
  C/Check_even_Odd.c
Labels: hacktoberfest-accepted

#274 Added a folder named Python with logic of Radix sort using Python lang
  Algorithms/Python/radixSort.py
Labels: Hacktoberfest, hacktoberfest-accepted

#275 Add files via upload
  Algorithms/C++/interval_queries.cpp.txt
Labels: Hacktoberfest, hacktoberfest-accepted

#288 Created Sieve of Eratosthenes
  Basic Programs/Sieve_of_Eratosthenes.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#303 Added Quantum Circuits made using Qiskit. These circuits in their cla…
  QuantumElectronics/QuantumDecoders.ipynb
  QuantumElectronics/QuantumHalfAdder.ipynb
  QuantumElectronics/QuantumMultiplexer.ipynb
  QuantumElectronics/QuatumFullAdder.ipynb
Labels: hacktoberfest-accepted

#306 Create Factorial.cpp
  Basic Programs/Factorial.cpp
Labels: hacktoberfest-accepted

#313 Permutation of A String
  Permutation of A String
Labels: good first issue, hacktoberfest-accepted

#316 Added One Greedy Algorithm
  Algorithms/C++/Greedy Algorithm/CoveringSegments
  Algorithms/C++/Greedy Algorithm/CoveringSegments.cpp
Labels: good first issue, hacktoberfest-accepted

#317 Create Permutation_Of_Array.cpp
  Basic Programs/Permutation_Of_Array.cpp
Labels: good first issue, hacktoberfest-accepted

#787 Added a new file"IPL_SCORE_VIEWER"
  IPL_SCORE_VIEWER.PY
Labels: good first issue, hacktoberfest-accepted

#344 Added java programmes
  Arrayintro.java
  AverageMarks.java
  BubbleSort.java
  SelectionSort.java
  TwoDArray.java
Labels: Hacktoberfest, hacktoberfest-accepted

#347 Create bubble_sort.cpp
  Basic Programs/CPP/bubble_sort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted
